# 共通部分をベースに、SSH server等を追加する
#   ENV CRAN="https://p3m.dev/cran/__linux__/noble/2025-06-12"

FROM mokztk/tidyverse_base:4.5.0

RUN /my_scripts/setup_sshd.sh

# SSH server を起動
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
