# 共通部分をベースにRStudio server等を追加する
#   ENV CRAN="https://p3m.dev/cran/__linux__/noble/2025-06-12"

FROM mokztk/tidyverse_base:4.5.0

# rocker/rstudio:4.5.0 の Dockerfile より流用
#  https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/r-ver_4.5.0.Dockerfile

ENV S6_VERSION="v2.1.0.2"
ENV RSTUDIO_VERSION="2025.05.1+513"
ENV DEFAULT_USER="rstudio"

COPY scripts/install_rstudio.sh /rocker_scripts/install_rstudio.sh
COPY scripts/install_s6init.sh /rocker_scripts/install_s6init.sh
#COPY scripts/default_user.sh /rocker_scripts/default_user.sh
COPY scripts/init_set_env.sh /rocker_scripts/init_set_env.sh
COPY scripts/init_userconf.sh /rocker_scripts/init_userconf.sh
COPY scripts/pam-helper.sh /rocker_scripts/pam-helper.sh
RUN /rocker_scripts/install_rstudio.sh

ENV LANG=ja_JP.UTF-8 \
    LC_ALL=ja_JP.UTF-8 \
    TZ=Asia/Tokyo \
    PASSWORD=password \
    DISABLE_AUTH=true \
    RUNROOTLESS=false

EXPOSE 8787
CMD ["/init"]
